import type { Metadata } from "next";
import Providers from "../lib/queryiesandMutations/provider";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={`  ${poppins.className}   antialiased`}>
          {children}
        </body>
      </Providers>
    </html>
  );
}
